spring:
  application:
    name: job-portal
  data:
    mongodb:
      uri: mongodb://localhost:27017/${DB_NAME}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${SERVER_PORT}
